version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /srv/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d 
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock
    restart: always
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /srv/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx
    restart: always
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /srv/mongodb:/data/db
    restart: always
    command: mongod
  kadira-engine:
    build: ./kadira-engine
    container_name: engine
    ports:
      - "11011:80"
    links:
      - mongodb
    environment:
      - PORT=80
      - MONGO_URL=mongodb://mongodb:27017/kadira
      - MONGO_SHARD_URL_one=mongodb://mongodb:27017/kadira
      - VIRTUAL_HOST=apm-engine.example.com
      - LETSENCRYPT_HOST=apm-engine.example.com
      - LETSENCRYPT_EMAIL=info@example.com
    restart: always
    depends_on:
      - mongodb
  kadira-rma:
    build: ./kadira-rma
    container_name: rma
    links:
      - mongodb
    environment:
      - MONGO_SHARD=one
      - MONGO_URL=mongodb://mongodb:27017/kadira
    restart: always
    depends_on:
      - mongodb
  kadira-ui:
    build: ./kadira-ui
    container_name: ui
    ports:
      - "4000:80"
    links:
      - mongodb
    environment:
      - PORT=80
      - ROOT_URL=https://apm.example.com
      - MONGO_URL=mongodb://mongodb:27017/kadira
      - MONGO_SHARD_URL_one=mongodb://mongodb:27017/kadira
      - VIRTUAL_HOST=apm.example.com
      - LETSENCRYPT_HOST=apm.example.com
      - LETSENCRYPT_EMAIL=info@example.com
      - METEOR_SETTINGS={"public":{"tender":{"key":"405871e6-4816-4d44-a0f3-860c0e988078"},"intercom":{},"loginState":{"domain":"","cookieName":"kadira-dev-login-state"}},"tender":{"secret":"71825e70-d11d-489b-b273-2afdca024fd6"},"stripe":{"amol":{"apiKey":"sk_test_tNO29lr3TPEvetcJfB4Vf54s","publishableKey":"pk_test_ZlbObLXALEa5wwBShlBitOS3","appName":"Kadira","appLogo":"https://kadira.io/favicon.ico"},"kadirahq":{"apiKey":"sk_test_22QITCBPhqEaEKjHXK5BBwO8","publishableKey":"pk_test_Tc1iVNRP9p8o7zgYWoWjZnm4","appName":"KadiraHQ","appLogo":"https://kadira.io/favicon.ico"}}}
    restart: always
    depends_on:
      - mongodb
